support body pose z by sending coords
sktometometo/jsk_robot pull request #84
Opened 2021-11-12 11:22 UTC by mqcmd196

2021-11-15 03:19 UTC, sktometometo requested changes
これだとwatch-dogデモが動かなくなるので、名前を変えて新しいメソッドにするかrpyとcoordsの両方を受け取れるようにするかしてください。

2021-11-15 03:19 UTC, mqcmd196 commented
@sktometometo 今その変更をしています

2021-11-15 04:28 UTC, mqcmd196 commented
https://github.com/sktometometo/jsk_robot/pull/84/commits/e04966cc48ba10655fd7ad6eb0e8e87581ecbc5a で対応しました．明日行ってテストする予定ですが早めに確認する必要があれば，誰かテストしてくれると助かります． cc: @708yamaguchi , @tkmtnt7000

2021-11-15 05:37 UTC, mqcmd196 commented
spotの姿勢でx,yは指定できないのですが，spotのロボットモデルと，fullbody-inverse-kinematicsとに適用しないといけなさそうですね

2021-11-15 05:44 UTC, tkmtnt7000 requested changes

2021-11-15 05:44 UTC, tkmtnt7000 commented on jsk_spot_robot/spoteus/spot-interface.l
> +     &key (topic-name "/spot/body_pose"))
I think these lines should be 
```
(&optional r p y coords  

 &key (topic-name "/spot/body_pose")
```
...?

2021-11-15 05:51 UTC, 708yamaguchi commented on jsk_spot_robot/spoteus/spot-interface.l
> +     &key (topic-name "/spot/body_pose"))
そうですね．
文法的には塚本君がいうのが正しいですね．
参考：
https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/df0fc28a965168744c7d2bd1dd57e6fca8fb9d29/pr2eus/robot-interface.l#L450-L451

あと僕が思ったのは，そもそも`(r p y coords)`をoptional引数にしていいのかな，というところです．
これだと，coordsのみを指定したいときに，r p yも指定しないといけないよね

だとしたら，
```
(pose &key (topic-name "/spot/body_pose"))
  (if (vectorp pose)
    (
    ;; poseが(float-vector r p y)だったときの処理
    )
  (if (coordsp pose)
    (
    ;; poseがcoordsだったときの処理
    )
```
みたいにする方がいいのかな（coordspみたいな関数があるかは不明）

2021-11-15 06:01 UTC, 708yamaguchi commented
> spotの姿勢でx,yは指定できないのですが，spotのロボットモデルと，fullbody-inverse-kinematicsとに適用しないといけなさそうですね

これに関してですが，spotのロボットモデルの動きは制限しなくていいかなと思いました．
spotのeusモデルはあくまでも幾何学的なモデルで，現実でのバランス制御などは考慮しなくていいと考えたからです．

一方で，fullbody-inverse-kinematicsなどではxy方向に動かさないためのオプションを付けられるとよいなと思いました．
このオプションがtだとcoordsに与えられた:posのxやy成分を0にしてIKを解く，みたいにできるといいですね．

変更しないといけない関数は意外と多くて，
sktometometo:develop/spot
- spot-utils.lの:body-inverse-kinematics
https://github.com/sktometometo/jsk_robot/blob/develop/spot/jsk_spot_robot/spoteus/spot-utils.l
- spotkinova.lの:body-inverse-kinematicsと:fullbody-inverse-kinematics（2種類*3つずつ）
https://github.com/sktometometo/jsk_robot/blob/develop/spot/jsk_spotkinova_robot/spotkinovaeus/spotkinova.l
sktometometo:PR/spot/add-jsk-spot-robot
- spot-utils.lの:body-inverse-kinematics
https://github.com/sktometometo/jsk_robot/blob/PR/spot/add-jsk-spot-robot/jsk_spot_robot/spoteus/spot-utils.l

2021-11-15 06:24 UTC, mqcmd196 commented on jsk_spot_robot/spoteus/spot-interface.l
> +     &key (topic-name "/spot/body_pose"))
I remember both can be used, does it return error?

2021-11-15 06:48 UTC, tkmtnt7000 commented on jsk_spot_robot/spoteus/spot-interface.l
> +     &key (topic-name "/spot/body_pose"))
Yes. I got following error.
```
2.irteusgl$ (send *ri* :body-pose 0 0 0)
Call Stack (max depth: 20):
  0: at (send *ri* :body-pose 0 0 0)
  1: at #<compiled-code #X55d1b98dae18>
/opt/ros/melodic/share/euslisp/jskeus/eus/Linux64/bin/irteusgl 0 error: keyword expected for arguments in (send *ri* :body-pose 0 0 0)
```

2021-11-15 07:50 UTC, sktometometo commented
@708yamaguchi develop/spotへPR出してくれれば, jsk-ros-pkg/master へのPRへ適宜cherry-pickしておくので, develop/spotブランチだけ気にしてください。

2021-11-15 08:00 UTC, 708yamaguchi commented
@sktometometo 

ああ，そうなんだ．
cherry-pick助かります．
ありがとう．

2021-11-15 10:41 UTC, mqcmd196 commented on jsk_spot_robot/spoteus/spot-interface.l
> +     &key (topic-name "/spot/body_pose"))
gomenn hontoda...

2021-11-16 05:23 UTC, mqcmd196 commented
@708yamaguchi @tkmtnt7000 バグ修正とアドバイスありがとうございます．

> (coordspみたいな関数があるかは不明）

ですが，なかったのでelse節にしました．jsk標準では座標の扱いは`make-coords`を使うことが多いので個人的には理にかなっていると思います．また実機での動作も確認しました．

2021-11-16 06:45 UTC, mqcmd196 commented
watchdogデモについてですが，このブランチを適用してlaunchすると
```
Call Stack (max depth: 20):
  0: at (apply #'send *ri* :body-pose target-rpy-euler)
  1: at (apply #'send *ri* :body-pose target-rpy-euler)
  2: at (send* *ri* :body-pose target-rpy-euler)
  3: at (let ((max-person-height 0) (target-person nil) (human-height-threshold (send *ri* :get-val 'hum
an-height-threshold)) (image-file-name nil) (current-time (unix:localtime)) target-rpy-euler) (if (< (el
t (send *ri* :get-val 'ypr-euler) 1) (* (send *ri* :get-val 'lookup-angle) 0.5)) (setq human_height_thre
shold (* (send *ri* :get-val 'human-height-threshold) 0.8))) (dolist (rect (send *ri* :get-val 'human-re
cts)) (when (and (< (send rect :width) (* (send *ri* :get-val 'human-width-threshold) (send rect :height
))) (> (send rect :height) (* (send *ri* :get-val 'human-height-threshold) (send *ri* :get-val 'paranoma
-height))) (> (send rect :height) max-person-height)) (setq max-person-height (send rect :height)) (setq
 target-person rect))) (if (null target-person) (setq target-rpy-euler '(0 0 0)) (progn (setq rel-yaw-an
gle (/ (* (* (- (/ (send *ri* :get-val 'paranoma-width) 2) (+ (send target-person :x) (/ (send target-pe
rson :width) 2))) 2.0) pi) (send *ri* :get-val 'paranoma-width))) (if (< (abs rel-yaw-angle) (send *ri* 
:get-val 'max-tracking-yaw)) (progn (setq target-rpy-euler (list 0 (send *ri* :get-val 'lookup-angle) (-
 (+ rel-yaw-angle (elt (send *ri* :get-val 'ypr-euler) 0)) (send *ri* :get-val 'yaw-offset)))) (ros::ros
-debug "find good person to look at: target-rpy-euler: ~A, rel-yaw: ~A body yaw: ~A, yaw offset: ~A" tar
get-rpy-euler rel-yaw-angle (elt (send *ri* :get-val 'ypr-euler) 0) (send *ri* :get-val 'yaw-offset)) (s
etq image-file-name (format nil "watchdog-demo-~A-~A-~A-~A-~A-~A.jpg" (+ 1900 (elt current-time 5)) (+ 4
 (elt current-time 4)) (elt current-time 3) (elt current-time 2) (elt current-time 1) (elt current-time 
0))) (send *ri* :capture-image image-file-name) (send *ri* :play-sound (send *ri* :get-val 'bark-sound))
) (setq target-rpy-euler '(0 0 0))))) (print target-rpy-euler) (send* *ri* :body-pose target-rpy-euler))
  4: at (while (not ret) (ros::spin-once) (send *ri* :spin-once) (setq ret (func-day-basic userdata-alis
t)) (if ret (return-from func-watch ret)) (when (> (/ (send (ros::time- (ros::time-now) (send *ri* :get-
val 'stand-start-time)) :to-sec) 60) (- 60 (send *ri* :get-val 'rest-time-per-hour))) (ros::ros-info "ha
ve a rest") (send *ri* :set-val 'stand-start-time (ros::time-now)) (send *ri* :sit) (send *ri* :power-of
f) (setq ret :sit) (return-from func-watch ret)) (when (send *ri* :high-battery-temp) (ros::ros-warn "th
e battery temperature is higher than the threshold: ~A vs ~A, sit down and turn off servo" (send *ri* :g
et-val 'battery-temp) (send *ri* :get-val 'temp-threshold-sit)) (send *ri* :set-val 'stand-start-time (r
os::time-now)) (send *ri* :sit) (send *ri* :power-off) (setq ret :sit) (return-from func-watch ret)) (le
t ((max-person-height 0) (target-person nil) (human-height-threshold (send *ri* :get-val 'human-height-t
hreshold)) (image-file-name nil) (current-time (unix:localtime)) target-rpy-euler) (if (< (elt (send *ri
* :get-val 'ypr-euler) 1) (* (send *ri* :get-val 'lookup-angle) 0.5)) (setq human_height_threshold (* (s
end *ri* :get-val 'human-height-threshold) 0.8))) (dolist (rect (send *ri* :get-val 'human-rects)) (when
 (and (< (send rect :width) (* (send *ri* :get-val 'human-width-threshold) (send rect :height))) (> (sen
d rect :height) (* (send *ri* :get-val 'human-height-threshold) (send *ri* :get-val 'paranoma-height))) 
(> (send rect :height) max-person-height)) (setq max-person-height (send rect :height)) (setq target-per
son rect))) (if (null target-person) (setq target-rpy-euler '(0 0 0)) (progn (setq rel-yaw-angle (/ (* (
* (- (/ (send *ri* :get-val 'paranoma-width) 2) (+ (send target-person :x) (/ (send target-person :width
) 2))) 2.0) pi) (send *ri* :get-val 'paranoma-width))) (if (< (abs rel-yaw-angle) (send *ri* :get-val 'm
ax-tracking-yaw)) (progn (setq target-rpy-euler (list 0 (send *ri* :get-val 'lookup-angle) (- (+ rel-yaw
-angle (elt (send *ri* :get-val 'ypr-euler) 0)) (send *ri* :get-val 'yaw-offset)))) (ros::ros-debug "fin
d good person to look at: target-rpy-euler: ~A, rel-yaw: ~A body yaw: ~A, yaw offset: ~A" target-rpy-eul
er rel-yaw-angle (elt (send *ri* :get-val 'ypr-euler) 0) (send *ri* :get-val 'yaw-offset)) (setq image-f
ile-name (format nil "watchdog-demo-~A-~A-~A-~A-~A-~A.jpg" (+ 1900 (elt current-time 5)) (+ 4 (elt curre
nt-time 4)) (elt current-time 3) (elt current-time 2) (elt current-time 1) (elt current-time 0))) (send 
*ri* :capture-image image-file-name) (send *ri* :play-sound (send *ri* :get-val 'bark-sound))) (setq tar
get-rpy-euler '(0 0 0))))) (print target-rpy-euler) (send* *ri* :body-pose target-rpy-euler)) (unix:usle
ep (floor (* (send *ri* :get-val 'change-body-duration) 1000000))))                                    
  5: at (let ((ret nil)) (while (not ret) (ros::spin-once) (send *ri* :spin-once) (setq ret (func-day-ba
sic userdata-alist)) (if ret (return-from func-watch ret)) (when (> (/ (send (ros::time- (ros::time-now)
 (send *ri* :get-val 'stand-start-time)) :to-sec) 60) (- 60 (send *ri* :get-val 'rest-time-per-hour))) (
ros::ros-info "have a rest") (send *ri* :set-val 'stand-start-time (ros::time-now)) (send *ri* :sit) (se
nd *ri* :power-off) (setq ret :sit) (return-from func-watch ret)) (when (send *ri* :high-battery-temp) (
ros::ros-warn "the battery temperature is higher than the threshold: ~A vs ~A, sit down and turn off ser
vo" (send *ri* :get-val 'battery-temp) (send *ri* :get-val 'temp-threshold-sit)) (send *ri* :set-val 'st
and-start-time (ros::time-now)) (send *ri* :sit) (send *ri* :power-off) (setq ret :sit) (return-from fun
c-watch ret)) (let ((max-person-height 0) (target-person nil) (human-height-threshold (send *ri* :get-va
l 'human-height-threshold)) (image-file-name nil) (current-time (unix:localtime)) target-rpy-euler) (if 
(< (elt (send *ri* :get-val 'ypr-euler) 1) (* (send *ri* :get-val 'lookup-angle) 0.5)) (setq human_heigh
t_threshold (* (send *ri* :get-val 'human-height-threshold) 0.8))) (dolist (rect (send *ri* :get-val 'hu
man-rects)) (when (and (< (send rect :width) (* (send *ri* :get-val 'human-width-threshold) (send rect :
height))) (> (send rect :height) (* (send *ri* :get-val 'human-height-threshold) (send *ri* :get-val 'pa
ranoma-height))) (> (send rect :height) max-person-height)) (setq max-person-height (send rect :height))
 (setq target-person rect))) (if (null target-person) (setq target-rpy-euler '(0 0 0)) (progn (setq rel-
yaw-angle (/ (* (* (- (/ (send *ri* :get-val 'paranoma-width) 2) (+ (send target-person :x) (/ (send tar
get-person :width) 2))) 2.0) pi) (send *ri* :get-val 'paranoma-width))) (if (< (abs rel-yaw-angle) (send
 *ri* :get-val 'max-tracking-yaw)) (progn (setq target-rpy-euler (list 0 (send *ri* :get-val 'lookup-ang
le) (- (+ rel-yaw-angle (elt (send *ri* :get-val 'ypr-euler) 0)) (send *ri* :get-val 'yaw-offset)))) (ro
s::ros-debug "find good person to look at: target-rpy-euler: ~A, rel-yaw: ~A body yaw: ~A, yaw offset: ~
A" target-rpy-euler rel-yaw-angle (elt (send *ri* :get-val 'ypr-euler) 0) (send *ri* :get-val 'yaw-offse
t)) (setq image-file-name (format nil "watchdog-demo-~A-~A-~A-~A-~A-~A.jpg" (+ 1900 (elt current-time 5)
) (+ 4 (elt current-time 4)) (elt current-time 3) (elt current-time 2) (elt current-time 1) (elt current
-time 0))) (send *ri* :capture-image image-file-name) (send *ri* :play-sound (send *ri* :get-val 'bark-s
ound))) (setq target-rpy-euler '(0 0 0))))) (print target-rpy-euler) (send* *ri* :body-pose target-rpy-e
uler)) (unix:usleep (floor (* (send *ri* :get-val 'change-body-duration) 1000000)))) ret)              
  6: at (funcall action userdata)
  7: at (funcall action userdata)
  8: at (cond ((send self :submachine) (send action :execute userdata :step step)) ((functionp action) (
funcall action userdata)) (t (send se [...]

2021-11-16 06:47 UTC, mqcmd196 commented
```
send *ri* :body-pose '(0.1 0.1 0.1)
send *ri* :body-pose (float-vector 0.1 0.1 0.1)
send *ri* :body-pose (make-coords :pos #f(0 0 -500))
```
の動作は確認済みです

2021-11-16 06:49 UTC, tkmtnt7000 approved these changes

2021-11-16 07:07 UTC, mqcmd196 commented
https://github.com/sktometometo/jsk_demos/pull/3 とこのブランチでwatch-dogデモが正常に動くことを確認しました

2021-11-16 07:57 UTC, merged

2021-11-16 17:02 UTC, 708yamaguchi commented
上のコメントの

> 一方で，fullbody-inverse-kinematicsなどではxy方向に動かさないためのオプションを付けられるとよいなと思いました．
> このオプションがtだとcoordsに与えられた:posのxやy成分を0にしてIKを解く，みたいにできるといいですね．
> 変更しないといけない関数は意外と多くて，

は、以下で解決しました。
https://github.com/sktometometo/jsk_robot/pull/86